CREATE TABLE LKP_PROGRAMMI (
    ID_PROGRAMMA                            VARCHAR2(100 CHAR) DEFAULT UUID(),
    VALORE_SEQUENZA_TEMPORALE_PROGRAMMA     INTEGER,
    NOME_PROGRAMMA                          VARCHAR2(500 CHAR),
    ORARIO_INIZIO_PROGRAMMA                 TIME,
    ORARIO_FINE_PROGRAMMA                   TIME,

    CONSTRAINT PK_LKP_PROGRAMMI PRIMARY KEY (ID_PROGRAMMA)
);


CREATE TABLE LKP_PIANTE_PROGRAMMI (
    ID_PIANTA                               VARCHAR2(100 CHAR),
    ID_PROGRAMMA                            VARCHAR2(100 CHAR),

    CONSTRAINT PK_LKP_PIANTE_PROGRAMMI PRIMARY KEY (ID_PIANTA, ID_PROGRAMMA),
    CONSTRAINT FK_LKP_PIANTE_PROGRAMMI_PIANTA FOREIGN KEY (ID_PIANTA) REFERENCES ACT_ANAGRAFICA_PIANTE_TESTATA(ID_PIANTA),
    CONSTRAINT FK_LKP_PIANTE_PROGRAMMI_PROGRAMMA FOREIGN KEY (ID_PROGRAMMA) REFERENCES LKP_PROGRAMMI(ID_PROGRAMMA)
);


CREATE TABLE LKP_STATI_PIANTE (
    ID_STATO                                VARCHAR2(500 CHAR),
    NOME_STATO                              VARCHAR2(500 CHAR),
    DESCRIZIONE_STATO                       CLOB,

    CONSTRAINT PK_LKP_STATI PRIMARY KEY (ID_STATO),
    CONSTRAINT CK_LKP_STATI CHECK (ID_STATO IN ('TROPPO_SECCO','SECCO','UMIDO','BAGNATO','TROPPO_BAGNATO'))
);


CREATE TABLE LKP_STANZE (
    ID_STANZA                               VARCHAR2(100 CHAR) DEFAULT UUID(),
    NOME_STANZA                             VARCHAR2(500 CHAR),
    DIMENSIONE_GRIGLIA_X                    INTEGER,
    DIMENSIONE_GRIGLIA_Y                    INTEGER,

    CONSTRAINT PK_LKP_STANZE PRIMARY KEY (ID_STANZA)
);