CREATE TABLE ACT_ANAGRAFICA_PIANTE_TESTATA (
    ID_PIANTA                       VARCHAR2(100 CHAR) DEFAULT UUID(),
    ID_STATO_PIANTA                 VARCHAR2(500 CHAR),
    ID_ULTIMO_PROGRAMMA_ESEGUITO    VARCHAR2(100 CHAR),
    DATA_INSERIMENTO                TIMESTAMP,
    DATA_ULTIMA_MODIFICA            TIMESTAMP,

    CONSTRAINT PK_ACT_ANAGRAFICA_TESTATA PRIMARY KEY (ID_PIANTA),
    CONSTRAINT FK_ACT_ANAGRAFICA_TESTATA_STATO FOREIGN KEY (ID_STATO_PIANTA) REFERENCES LKP_STATI_PIANTE(ID_STATO),
    CONSTRAINT FK_ACT_ANAGRAFICA_TESTATA_PROGRAMMA FOREIGN KEY (ID_ULTIMO_PROGRAMMA_ESEGUITO) REFERENCES LKP_PROGRAMMI(ID_PROGRAMMA)
);


CREATE TABLE ACT_ANAGRAFICA_PIANTE_DETTAGLIO (
    ID_PIANTA                       VARCHAR2(100 CHAR),
    NOME_PIANTA                     VARCHAR2(500 CHAR),
    DESCRIZIONE_PIANTA              CLOB,
    FOTO_PIANTA                     BLOB,
    ID_STANZA                       VARCHAR2(100 CHAR),
    POSIZIONE_STANZA_X              INTEGER,
    POSIZIONE_STANZA_Y              INTEGER,

    CONSTRAINT PK_ACT_ANAGRAFICA_DETTAGLIO PRIMARY KEY (ID_PIANTA),
    CONSTRAINT FK_ACT_ANAGRAFICA_DETTAGLIO_PIANTA FOREIGN KEY (ID_PIANTA) REFERENCES ACT_ANAGRAFICA_PIANTE_TESTATA(ID_PIANTA),
    CONSTRAINT FK_ACT_ANAGRAFICA_DETTAGLIO_STANZA FOREIGN KEY (ID_STANZA) REFERENCES LKP_STANZE(ID_STANZA)
);


CREATE TABLE ACT_ANAGRAFICA_PIANTE_DETTAGLIO_SENSORI (
    ID_PIANTA                       VARCHAR2(100 CHAR),
    UMIDITA_CORRENTE                INTEGER,
    ACQUA_ULTIMA_INNAFFIATURA       INTEGER,
    ALTRO_DATO_SENSORI_1            DECIMAL(5,2),
    ALTRO_DATO_SENSORI_2            DECIMAL(5,2),
    ALTRO_DATO_SENSORI_3            DECIMAL(5,2),
    ALTRO_DATO_SENSORI_4            DECIMAL(5,2),

    CONSTRAINT PK_ACT_ANAGRAFICA_DETTAGLIO_SENSORI PRIMARY KEY (ID_PIANTA),
    CONSTRAINT FK_ACT_ANAGRAFICA_DETTAGLIO_SENSORI_PIANTA FOREIGN KEY (ID_PIANTA) REFERENCES ACT_ANAGRAFICA_PIANTE_TESTATA(ID_PIANTA),
);


CREATE TABLE HIS_ANAGRAFICA_PIANTE_DETTAGLIO_SENSORI (
    ID_PIANTA                       VARCHAR2(100 CHAR),
    ID_STATO_PIANTA                 VARCHAR2(500 CHAR),
    ID_PROGRAMMA_ESEGUITO           VARCHAR2(100 CHAR),
    UMIDITA_CORRENTE                INTEGER,
    ACQUA_ULTIMA_INNAFFIATURA       INTEGER,
    ALTRO_DATO_SENSORI_1            DECIMAL(5,2),
    ALTRO_DATO_SENSORI_2            DECIMAL(5,2),
    ALTRO_DATO_SENSORI_3            DECIMAL(5,2),
    ALTRO_DATO_SENSORI_4            DECIMAL(5,2),
    DATA_MODIFICA                   TIMESTAMP,

    CONSTRAINT FK_HIS_ANAGRAFICA_DETTAGLIO_SENSORI_PIANTA FOREIGN KEY (ID_PIANTA) REFERENCES ACT_ANAGRAFICA_PIANTE_TESTATA(ID_PIANTA),
    CONSTRAINT FK_HIS_ANAGRAFICA_DETTAGLIO_SENSORI_STATO FOREIGN KEY (ID_STATO_PIANTA) REFERENCES LKP_STATI_PIANTE(ID_STATO),
    CONSTRAINT FK_HIS_ANAGRAFICA_DETTAGLIO_SENSORI_PROGRAMMA FOREIGN KEY (ID_PROGRAMMA_ESEGUITO) REFERENCES LKP_PROGRAMMI(ID_PROGRAMMA)
);